#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/plexd
CONF=/etc/plexd/config.yaml

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" up --config "$CONF"
	# threshold 60s, restart delay 5s, give up after 5 fast crashes
	procd_set_param respawn 60 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file "$CONF"
	procd_close_instance
}
